#!/bin/bash


port=$2
htmlfiles="$(cd $3; pwd)"
cd "$1"

tube=/tmp/requete
mkfifo $tube 

while true ; do
	echo "-----------------" >&2
	cat $tube |process-request "$htmlfiles"|nc -i 0 -l $port > $tube
done

