#!/bin/bash

case $1 in 

*.png )
    echo "image/png"
    exit 0
;;

*.pdf )
    echo "application/pdf"
    exit 0
;;

*.html )
    echo "text/html"
    exit 0
;;

*.gif )
    echo "image/gif"
    exit 0
;;

*.jp*g )
    echo "image/jpeg"
    exit 0
;;

* )
    echo "text/html"
    exit 0
;;
esac