#!/bin/bash

empty=`printf "\r"`
echo "HTTP/1.1 403 FORBIDDEN$empty"
echo "Content-Length: 16$empty"
echo "Content-Type: text/html$empty"
echo "$empty"
echo "Access forbidden"
echo "Erreur : " 403 >&2 
echo "Access forbidden" >&2